[20:42:04 - main - INFO] Waiting for JIT...
[20:42:55 - main - INFO] ---------------------------
[20:42:55 - main - INFO] Iter:   0    Time: 50.918
[20:42:55 - main - INFO] -----------  --------------
[20:42:55 - main - INFO] ics_loss     3.909e-01
[20:42:55 - main - INFO] res_loss     7.466e+00
[20:42:55 - main - INFO] l2_error     1.294e+00
Traceback (most recent call last):
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/main.py", line 40, in <module>
    app.run(main)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/main.py", line 32, in main
    train.train_and_evaluate(FLAGS.config, FLAGS.workdir)
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/jaxpi/examples/allen_cahn/train.py", line 99, in train_and_evaluate
    batch = next(res_sampler)
            ^^^^^^^^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jaxpi/samplers.py", line 20, in __getitem__
    batch = self.data_generation(keys)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ananyaebhartari/Documents/Paris/My_pirate/.venv1/lib/python3.11/site-packages/jax/_src/api.py", line 1831, in <lambda>
    lambda x, s: pxla.shard_args([s], [None], [x])[0],

KeyboardInterrupt
